# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PlayWithArithmetics.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import main as mn


class Ui_MainWindow(object):

    def __init__(self):
        self.centralwidget = None
        self.gridLayout = None
        self.gridLayout_2 = None
        self.gridLayout_3 = None

        self.label = None
        self.label_2 = None
        self.label_3 = None
        self.label_4 = None
        self.label_5 = None
        self.label_6 = None
        self.label_7 = None
        self.label_8 = None
        self.label_9 = None
        self.label_10 = None
        self.label_11 = None

        self.lineEdit = None
        self.lineEdit_2 = None
        self.lineEdit_3 = None
        self.lineEdit_4 = None
        self.lineEdit_5 = None
        self.lineEdit_6 = None

        self.pushButton = None
        self.pushButton_2 = None
        self.pushButton_3 = None
        self.pushButton_4 = None
        self.pushButton_5 = None
        self.pushButton_6 = None
        self.pushButton_7 = None

        self.lcdNumber = None
        self.line = None
        self.progressBar = None

        self.passingEquationAnswer = ""

        self.gridLayout2Elements = []
        self.gridLayout3Elements = []

        self.sessionCounter = 1
        self.generatingEquationsObject = None
        self.generated_equation_with_its_result = []
        self.equation_and_result = []
        self.counter = 20
        self.timer = None
        self.progressBarCounter = 0

    def setupUi(self, _MainWindow):

        # Setting some properties of the main window
        _MainWindow.setWindowIcon(QtGui.QIcon('formula-fx-icon.png'))
        _MainWindow.setObjectName("_MainWindow")
        _MainWindow.resize(656, 599)
        _MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)

        # Defining the central widget object
        self.centralwidget = QtWidgets.QWidget(_MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")

        # Defining the main grid layout
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")

        # Defining the first sub-grid layout
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_2.setObjectName("gridLayout_2")

        # Defining the second sub-grid layout
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")

        # Embedding sub-grid layouts into the basic grid layout
        self.gridLayout.addLayout(self.gridLayout_2, 0, 0, 1, 1)

        # LABEL ELEMENTS

        # First label:
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setEnabled(True)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(size_policy)
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
                                 "background-color: rgb(0, 0, 0);\n"
                                 "border-color: rgb(255, 0, 0);\n"
                                 "font: 12.5pt \"MS Shell Dlg 2\";")
        self.label.setLineWidth(1)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 1, 1, 1, 4)

        # Exception: a push button to retry the arithmetic game
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.pushButton_7.sizePolicy().hasHeightForWidth())
        self.pushButton_7.setSizePolicy(size_policy)
        self.pushButton_7.setStyleSheet("QPushButton {\n"
                                        "background-color: black;\n"
                                        "border: 2px solid white;\n"
                                        "font: 12pt \"MS Shell Dlg 2\";\n"
                                        "color: white;\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton:hover {\n"
                                        "background-color: white;\n"
                                        "color: black;\n"
                                        "border: 2px solid black;\n"
                                        "}")
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout_2.addWidget(self.pushButton_7, 2, 1, 1, 4)

        # Second label:
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(size_policy)
        self.label_2.setStyleSheet("border-color: rgb(255, 0, 0);\n"
                                   "font: 12pt \"MS Shell Dlg 2\";")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 5, 0, 1, 1)

        # Third label:
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setEnabled(True)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(size_policy)
        self.label_3.setStyleSheet("border-color: rgb(255, 0, 0);\n"
                                   "font: 12pt \"MS Shell Dlg 2\";")
        self.label_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 4, 0, 1, 1)

        # Fourth label:
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setEnabled(True)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(size_policy)
        self.label_4.setStyleSheet("border-color: rgb(255, 0, 0);\n"
                                   "font: 12pt \"MS Shell Dlg 2\";")
        self.label_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 1, 0, 1, 1)

        # Fifth label:
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);\n"
                                   "background-color: rgb(0, 0, 0);\n"
                                   "border-color: rgb(255, 0, 0);\n"
                                   "font: 12.5pt \"MS Shell Dlg 2\";")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 1, 0, 1, 1)

        # Sixth label:
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setStyleSheet("border-color: rgb(255, 0, 0);\n"
                                   "font: 12pt \"MS Shell Dlg 2\";")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 3, 0, 1, 1)

        # Seventh label:
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(size_policy)
        self.label_7.setStyleSheet("border-color: rgb(255, 0, 0);\n"
                                   "font: 12pt \"MS Shell Dlg 2\";")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 6, 0, 1, 1)

        # Eighth label:
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setStyleSheet("color: rgb(255, 255, 255);\n"
                                   "background-color: rgb(0, 0, 0);\n"
                                   "border-color: rgb(255, 0, 0);\n"
                                   "font: 12.5pt \"MS Shell Dlg 2\";")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 0, 0, 1, 2)
        self.gridLayout.addLayout(self.gridLayout_3, 1, 0, 1, 1)
        _MainWindow.setCentralWidget(self.centralwidget)

        # Ninth label:
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(size_policy)
        self.label_9.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_9, 6, 4, 1, 1)

        # Tenth label:
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setEnabled(True)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(size_policy)
        self.label_10.setStyleSheet("border-color: rgb(255, 0, 0);\n"
                                    "font: 12pt \"MS Shell Dlg 2\";")
        self.label_10.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_10, 7, 0, 1, 1)

        # Eleventh label:
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setEnabled(True)
        self.label_11.setStyleSheet("border-color: rgb(255, 0, 0);\n"
                                    "font: 12pt \"MS Shell Dlg 2\";")
        self.label_11.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_11, 12, 1, 1, 1)

        # LINE EDIT ELEMENTS

        # First line edit:
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.lineEdit.setSizePolicy(size_policy)
        self.lineEdit.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setClearButtonEnabled(False)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_2.addWidget(self.lineEdit, 4, 1, 1, 3)

        # Second line edit:
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setEnabled(False)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.lineEdit_2.sizePolicy().hasHeightForWidth())
        self.lineEdit_2.setSizePolicy(size_policy)
        self.lineEdit_2.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_2.addWidget(self.lineEdit_2, 7, 1, 1, 3)

        # Third line edit:
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.lineEdit_3.sizePolicy().hasHeightForWidth())
        self.lineEdit_3.setSizePolicy(size_policy)
        self.lineEdit_3.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.lineEdit_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_2.addWidget(self.lineEdit_3, 6, 1, 1, 1)

        # Fourth line edit:
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.lineEdit_4.sizePolicy().hasHeightForWidth())
        self.lineEdit_4.setSizePolicy(size_policy)
        self.lineEdit_4.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.lineEdit_4.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_4.setReadOnly(True)
        self.lineEdit_4.setClearButtonEnabled(False)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout_3.addWidget(self.lineEdit_4, 1, 1, 1, 1)

        # Fifth line edit:
        self.lineEdit_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_5.setEnabled(False)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.lineEdit_5.sizePolicy().hasHeightForWidth())
        self.lineEdit_5.setSizePolicy(size_policy)
        self.lineEdit_5.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.lineEdit_5.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_5.setReadOnly(True)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout_3.addWidget(self.lineEdit_5, 5, 0, 1, 2)

        # Sixth line edit:
        self.lineEdit_6 = QtWidgets.QLineEdit(self.centralwidget)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.lineEdit_6.sizePolicy().hasHeightForWidth())
        self.lineEdit_6.setSizePolicy(size_policy)
        self.lineEdit_6.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_6.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.gridLayout_3.addWidget(self.lineEdit_6, 3, 1, 1, 1)

        # PUSH BUTTON ELEMENTS

        # First push button:
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(size_policy)
        self.pushButton.setStyleSheet("QPushButton {\n"
                                      "background-color: black;\n"
                                      "border: 2px solid white;\n"
                                      "font: 12pt \"MS Shell Dlg 2\";\n"
                                      "color: white;\n"
                                      "}\n"
                                      "\n"
                                      "QPushButton:hover {\n"
                                      "background-color: white;\n"
                                      "color: black;\n"
                                      "border: 2px solid black;\n"
                                      "}")
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_2.addWidget(self.pushButton, 3, 1, 1, 3)

        # Second push button:
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(size_policy)
        self.pushButton_2.setStyleSheet("QPushButton {\n"
                                        "background-color: black;\n"
                                        "border: 2px solid white;\n"
                                        "font: 12pt \"MS Shell Dlg 2\";\n"
                                        "color: white;\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton:hover {\n"
                                        "background-color: white;\n"
                                        "color: black;\n"
                                        "border: 2px solid black;\n"
                                        "}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_2.addWidget(self.pushButton_2, 6, 3, 1, 1)
        self.pushButton_2.clicked.connect(self.checking_answer)

        # Third push button:
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(size_policy)
        self.pushButton_3.setStyleSheet("QPushButton {\n"
                                        "background-color: black;\n"
                                        "border: 2px solid white;\n"
                                        "font: 12pt \"MS Shell Dlg 2\";\n"
                                        "color: white;\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton:hover {\n"
                                        "background-color: white;\n"
                                        "color: black;\n"
                                        "border: 2px solid black;\n"
                                        "}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_2.addWidget(self.pushButton_3, 10, 1, 1, 3)

        # Fourth push button:
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(size_policy)
        self.pushButton_4.setStyleSheet("QPushButton {\n"
                                        "background-color: black;\n"
                                        "border: 2px solid white;\n"
                                        "font: 12pt \"MS Shell Dlg 2\";\n"
                                        "color: white;\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton:hover {\n"
                                        "background-color: white;\n"
                                        "color: black;\n"
                                        "border: 2px solid black;\n"
                                        "}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_3.addWidget(self.pushButton_4, 4, 0, 1, 2)

        # Fifth push button:
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.pushButton_5.sizePolicy().hasHeightForWidth())
        self.pushButton_5.setSizePolicy(size_policy)
        self.pushButton_5.setStyleSheet("QPushButton {\n"
                                        "background-color: black;\n"
                                        "border: 2px solid white;\n"
                                        "font: 12pt \"MS Shell Dlg 2\";\n"
                                        "color: white;\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton:hover {\n"
                                        "background-color: white;\n"
                                        "color: black;\n"
                                        "border: 2px solid black;\n"
                                        "}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_2.addWidget(self.pushButton_5, 8, 1, 1, 3)

        # Sixth push button:
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.pushButton_6.sizePolicy().hasHeightForWidth())
        self.pushButton_6.setSizePolicy(size_policy)
        self.pushButton_6.setStyleSheet("QPushButton {\n"
                                        "background-color: black;\n"
                                        "border: 2px solid white;\n"
                                        "font: 12pt \"MS Shell Dlg 2\";\n"
                                        "color: white;\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton:hover {\n"
                                        "background-color: white;\n"
                                        "color: black;\n"
                                        "border: 2px solid black;\n"
                                        "}")
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_2.addWidget(self.pushButton_6, 9, 1, 1, 3)

        # LCD NUMBER ELEMENTS

        # First lcd number:
        self.lcdNumber = QtWidgets.QLCDNumber(self.centralwidget)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.lcdNumber.sizePolicy().hasHeightForWidth())
        self.lcdNumber.setSizePolicy(size_policy)
        self.lcdNumber.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.lcdNumber.setObjectName("lcdNumber")
        self.lcdNumber.setProperty("value", 20)
        self.gridLayout_2.addWidget(self.lcdNumber, 5, 1, 1, 3)

        # LINE ELEMENTS

        # First line:
        self.line = QtWidgets.QFrame(self.centralwidget)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(size_policy)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 11, 1, 1, 3)

        # PROGRESS BAR ELEMENTS

        # First progress bar:
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.progressBar.setObjectName("progressBar")
        self.progressBar.setProperty("value", 0)
        self.gridLayout_2.addWidget(self.progressBar, 12, 3, 1, 1)

        # Re-translating main window labels and push buttons
        self.re_translateUi(_MainWindow)

        # Connecting slots of the main window object, by names
        QtCore.QMetaObject.connectSlotsByName(_MainWindow)

        # Upon executing this function, these things should be executed as well:

        self.gridLayout2Elements = [self.label, self.label_2, self.label_3, self.label_5, self.label_7,
                                    self.label_9, self.label_10, self.label_11, self.line, self.lineEdit,
                                    self.lineEdit_2, self.lineEdit_3, self.pushButton, self.pushButton_2,
                                    self.pushButton_3, self.pushButton_7, self.lcdNumber, self.progressBar]
        self.gridLayout3Elements = [self.label_4, self.label_6, self.label_8, self.lineEdit_4, self.lineEdit_5,
                                    self.lineEdit_6, self.pushButton_4]

        for element in self.gridLayout2Elements:
            element.hide()

        self.pushButton_5.hide()
        self.pushButton_6.hide()

        self.lineEdit_3.setReadOnly(True)
        self.pushButton_2.setEnabled(False)
        self.pushButton_3.setEnabled(False)

        self.pushButton.clicked.connect(self.stage_renderer)
        self.pushButton_3.clicked.connect(self.restoring_defaults)
        self.pushButton_4.clicked.connect(self.system_authenticator)

        self.equation_and_result = self.getting_equation_with_its_result()
        self.lineEdit_4.setText(self.equation_and_result[0])

    def re_translateUi(self, _MainWindow):
        _translate = QtCore.QCoreApplication.translate
        _MainWindow.setWindowTitle(_translate("_MainWindow", "Play With Arithmetics"))
        self.label.setText(_translate("_MainWindow", "Play With Arithmetics"))
        self.label_2.setText(_translate("_MainWindow", "Countdown Timer"))
        self.label_3.setText(_translate("_MainWindow", "Problem To Be Solved"))
        self.label_4.setText(_translate("_MainWindow", "Solve This To Pass"))
        self.label_5.setText(_translate("_MainWindow", "Session 1"))
        self.label_6.setText(_translate("_MainWindow", "Your Answer"))
        self.label_7.setText(_translate("_MainWindow", "Submit Your Answer"))
        self.label_8.setText(_translate("_MainWindow", "Arithmetic Game Gateway"))
        self.label_9.setText(_translate("_MainWindow", "Answer Status"))
        self.label_10.setText(_translate("_MainWindow", "Right Answer"))
        self.label_11.setText(_translate("_MainWindow", "Session\'s Progress"))
        self.pushButton.setText(_translate("_MainWindow", "Start Session"))
        self.pushButton_2.setText(_translate("_MainWindow", "Submit"))
        self.pushButton_3.setText(_translate("_MainWindow", "End Session"))
        self.pushButton_4.setText(_translate("_MainWindow", "Submit Answer"))
        self.pushButton_5.setText(_translate("_MainWindow", "Try This Stage Again!"))
        self.pushButton_6.setText(_translate("_MainWindow", "Go To Next Stage"))
        self.pushButton_7.setText(_translate("_MainWindow", "Take Another Journey!"))

    def system_authenticator(self):
        self.passingEquationAnswer = self.lineEdit_6.text().strip()
        if self.passingEquationAnswer != "":
            if str(self.equation_and_result[1]) == self.lineEdit_6.text().strip():
                for element in self.gridLayout3Elements:
                    element.hide()
                for element in self.gridLayout2Elements:
                    element.show()
                self.pushButton_7.hide()
            else:
                self.lineEdit_5.setText("Wrong answer! Try again!")

    def lcd_countdown_timer(self):
        self.lcdNumber.display(self.counter)
        if self.counter == 0:
            self.timer.stop()
            self.lineEdit_2.setText(str(self.generated_equation_with_its_result[1]))
            self.lineEdit_3.setText("")
            self.lineEdit_3.setReadOnly(True)
            self.pushButton_5.show()
            self.pushButton_2.setEnabled(False)
            self.label_9.setText("Time's out!")
            self.pushButton_5.clicked.connect(self.stage_renderer)
            self.counter = 20
            return
        self.counter -= 1

    def stage_renderer(self):
        self.pushButton.setEnabled(False)
        self.lineEdit_3.setReadOnly(False)
        self.pushButton_2.setEnabled(True)
        self.pushButton_3.setEnabled(True)

        self.timer = QtCore.QTimer()
        self.lineEdit.setEnabled(True)
        self.lineEdit_3.setEnabled(True)
        self.lineEdit.setText("")
        self.lineEdit_2.setText("")
        self.lineEdit_3.setText("")
        self.pushButton_5.hide()
        self.pushButton_6.hide()
        self.lcdNumber.setProperty("value", self.counter)
        self.pushButton_2.setText("Submit")
        self.label_9.setText("Answer Status")
        self.generatingEquationsObject = mn.GeneratingEquations()
        self.generated_equation_with_its_result = self.generatingEquationsObject.equation_assembly(
            self.generatingEquationsObject)
        self.lineEdit.setText(self.generated_equation_with_its_result[0])
        self.lcdNumber.setDigitCount(2)
        self.timer.timeout.connect(self.lcd_countdown_timer)
        self.timer.start(1000)

    def getting_equation_with_its_result(self):
        self.generatingEquationsObject = mn.GeneratingEquations()
        self.generated_equation_with_its_result = self.generatingEquationsObject.equation_assembly(
            self.generatingEquationsObject)
        return self.generated_equation_with_its_result

    def checking_answer(self):
        if self.lineEdit_3.text().strip() == "":
            return
        if self.lineEdit_3.text().strip() == str(self.generated_equation_with_its_result[1]):
            self.timer.stop()
            self.lineEdit_3.setReadOnly(True)
            self.pushButton_2.setEnabled(False)
            self.label_9.setText("Right!")
            self.progressBarCounter += 10
            self.progressBar.setProperty("value", self.progressBarCounter)

            if self.progressBarCounter == 100:
                self.progressBarCounter = -10
                self.sessionCounter += 1
                self.label_5.setText(f"Session {self.sessionCounter}")

                if self.sessionCounter == 10:
                    self.sessionCounter = 0
                    for element in self.gridLayout2Elements:
                        element.hide()
                    self.pushButton_6.hide()
                    self.label.show()
                    self.label.setText("Congratulations! You Have Won!")
                    self.pushButton_7.show()
                    self.pushButton_7.clicked.connect(self.retrying_journey)
                    return

            self.pushButton_6.show()
            self.counter = 20
            self.pushButton_6.clicked.connect(self.stage_renderer)
        else:
            self.label_9.setText("Wrong!")

    def restoring_defaults(self):
        self.passingEquationAnswer = ""
        self.sessionCounter = 1
        self.generatingEquationsObject = None
        self.generated_equation_with_its_result = []
        self.counter = 20
        self.timer = None
        self.progressBarCounter = 0

        self.label_5.setText("Session 1")

        self.lineEdit.setText("")
        self.lineEdit_2.setText("")
        self.lineEdit_3.setText("")
        self.lineEdit_4.setText("")
        self.lineEdit_5.setText("")
        self.lineEdit_6.setText("")

        self.pushButton.setEnabled(True)
        self.lineEdit_3.setReadOnly(True)
        self.pushButton_2.setEnabled(False)
        self.pushButton_3.setEnabled(False)

        self.pushButton_5.hide()
        self.pushButton_6.hide()

        self.lcdNumber.setProperty("value", 20)

        self.progressBar.setProperty("value", 0)

    def retrying_journey(self):
        self.label.hide()
        self.label.setText("Play With Arithmetics")
        self.pushButton_7.hide()
        for element in self.gridLayout2Elements:
            if element == self.pushButton_7:
                continue
            element.show()
        self.restoring_defaults()


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    _MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(_MainWindow)
    _MainWindow.show()
    sys.exit(app.exec_())
